# Generated by Django 5.1.13 on 2025-11-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('estudio_desarrollo_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.sede')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='videojuego_plataformas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.plataforma')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appexamen.videojuego')),
            ],
        ),
        migrations.AddField(
            model_name='plataforma',
            name='videojuego',
            field=models.ManyToManyField(through='appexamen.videojuego_plataformas', to='appexamen.videojuego'),
        ),
    ]
