# Generated by Django 5.1.13 on 2025-11-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexamen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='videojuego',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appexamen.videojuego'),
        ),
    ]
